" indentacion
set tabstop=2
set shiftwidth=2
set expandtab
set smartindent
set showmatch

" tema
"set termguicolors
"set background=dark
"colorscheme retrobox
" linea
syntax on
set number
set relativenumber

" key bindings
let mapleader=" "

noremap <leader>x :LspDocumentDiagnostics<CR>
noremap <leader>rn :LspRename<CR>
noremap <leader>e :Ex<CR>

" auto pairs
inoremap ( ()<Left>
inoremap [ []<Left>
inoremap { {}<Left>
inoremap " ""<Left>
inoremap ' ''<Left>

" Plugins

call plug#begin('~/.vim/plugged')
Plug 'prabirshrestha/vim-lsp'
Plug 'mattn/vim-lsp-settings'
call plug#end()

" formatting
augroup markdown_format
  autocmd!
  autocmd FileType markdown setlocal wrap linebreak breakindent
augroup END

" autocompletado
set omnifunc=lsp#complete

" Netrw
let g:netrw_keepdir = 0 " seguir navegacion como cwd
let g:netrw_banner = 0  " quitar banner
let g:netrw_sort_by = "time" 
let g:netrw_sort_direction = "reverse" " newest first
let g:netrw_liststyle = 1
let g:netrw_winsize = 30
let g:netrw_alto = 1 " split debajo
let g:netrw_home = "~/.config/vim/bookmarks"

" vimwiki
set nocompatible
filetype plugin on
let g:vimwiki_list = [{ 'syntax': 'markdown', 'ext': 'md'},
      \ {'syntax': 'markdown', 'ext': 'md', 'path': '~/vimwiki/blog', 'path_html': '~/website/'}, 
      \ {'syntax': 'markdown', 'ext': 'md', 'path': '~/vimwiki/devops'}]
nnoremap <leader>wf :call WikiFind()<CR>
  function! WikiFind()
    let l:term = input('Search:')
    if l:term == ''
      return
    endif
    execute 'VWS /' . escape(l:term,'/\') . '/'
  endfunction
