#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

$HOME/.config/scripts/handle-screen & 

bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a "*:qutebrowser" desktop=^1 follow=on state=fullscreen
bspc rule -a "*:Alacritty" desktop=^3 follow=on state=fullscreen
bspc rule -a "*:mpv" desktop=^2 follow=false state=fullscreen
