#! /usr/bin/env bash

pgrep -x sxhkd > /dev/null || sxhkd &


screens=($(xrandr | grep " connected" | awk '{print $1}'))

if [[ ${#screens[@]} -eq 1 ]] ; then
  bspc monitor -d I II III
else
 bspc monitor ${screens[0]} -d L1
 bspc monitor ${screens[1]} -d R1 R2
fi

bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a "*:qutebrowser" desktop=^2 follow=on state=fullscreen
bspc rule -a "*:Alacritty" desktop=^1 follow=on state=fullscreen
bspc rule -a "*:mpv" desktop=^3 follow=false state=fullscreen
