#!/usr/bin/env bash

LOG="/tmp/handle-screen.log"
# localizar las pantallas conectadas
logger start
screens=($(xrandr --query | grep " connected" | awk '{print $1}'))

logger "screens ${screens}"
logger "queried state of monitors $(echo $(bspc query -M --names))"
logger "queried state of monitors $(echo $(bspc query -D --names))"

bspc monitor -r

if [[ ${#screens[@]} -eq 1 ]] ; then
  # solo hay una pantalla
  logger "there is only one monitor"
  bspc monitor -d I II
else

 # hay mas de una pantalla (de momento solo hacemos handle de dos, y asumimos que la segunda esta a la izquierda)
 logger "there is more than one monitor (${#screens[@]})" 
 xrandr --output "${screens[1]}" --left-of "${screens[0]}" --primary 
 bspc monitor ${screens[1]} -d I
 bspc monitor ${screens[0]} -d II
fi
