#!/usr/bin/env bash

LOG="/tmp/handle-screen.log"
# localizar las pantallas conectadas
logging --start
screens=($(xrandr --query | grep " connected" | awk '{print $1}'))

logging "screens ${screens}"
logging "queried state of monitors $(echo $(bspc query -M --names))"
logging "queried state of monitors $(echo $(bspc query -D --names))"

bspc monitor -r

if [[ ${#screens[@]} -eq 1 ]] ; then
  # solo hay una pantalla
  logging "there is only one monitor"
  bspc monitor -d I II III
else

 # hay mas de una pantalla (de momento solo hacemos handle de dos, y asumimos que la segunda esta a la izquierda)
 logging "there is more than one monitor (${#screens[@]})" 
 xrandr --output "${screens[1]}" --left-of "${screens[0]}" --primary 
 bspc monitor ${screens[0]} -d III
 bspc monitor ${screens[1]} -d I II
fi

bspc wm -o
