#!/usr/bin/env bash

LOGDIR="$HOME/.local/log"

mkdir -p $LOGDIR

log_file() {
  local name
  name=$(caller_name)
  echo "$LOGDIR/$name.log"
}

logger() {
  local file

  case "$1" in
    -h|--help)
      cat << 'EOF'
logger [-s,--start|-e,--error|-w,--warning|-h|--help|-f, --finish] [STRING]
usage
  logger -s
  logger "hello world"
  logger -e "some pesky error"
options
  -e, --error     formatea el mensaje como error
  -f, --finish    crea el mensaje de salida de ejecucion
  -h, --help      muestra los comandos permitidos 
  -s, --start     crea el mensaje de inicio de ejecucion, debe usarse antes de loggear
  -w, --warning   formatea el mensaje como warning
EOF
      ;; 
    -s|--start)
      file=$(log_file)
      echo "---start $(date) ---" >> "$file"
      ;;
    -e|--error)
      echo "\033[31m$(date +%I) ERROR:\033[0m $*" >> "$file"
      ;;
     -w|--warning)
      echo "\033[33m$(date +%I) WARN:\033[0m $*" >> "$file"
      ;;
    -f|--finish)
      echo "bye!" >> "$file"
      echo "--- finish $(date) ---" >> "$file"
      ;;
    *)
      echo "$(date +%I) INFO: $*" >> "$file"
    ;;
esac
}

