unbind %
bind | split-window -h
unbind '"'
bind - split-window -v

unbind Left
unbind Right
unbind Up
unbind Down
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind h select-pane -L

bind J resize-pane -D 5
bind K resize-pane -U 5
bind L resize-pane -R 5
bind H resize-pane -L 5

set -sg escape-time 10

bind -r m resize-pane -Z

# NOTE getip es un script personal
set -g status-right "IP #(getip) BAT #(cat /sys/class/power_supply/BAT0/capacity) | #(date +%D) "
