#!/usr/bin/env bash

#
# clipboard functions
#

# yank last on history
yin() {
  fc -ln -1 | xclip -selection clipboard
}
# para copiar el output de la orden
yout() {
 "$@" 2>&1 | tee /tmp/last | xclip -selection clipboard
}


#
# colored output
#
ccat() {
    echo -e "$(cat $*)"
  }

#
# documentation (for example `docs k8s`)
#
docs(){
  tool=$1
  cat $HOME/documentation/"$tool" | fzf | xargs -I {} sh -c 'readonly {} | w3m -T text/html -dump | less'
}
